server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp # Replace with your DB URL
    username: root                      # Replace with your DB username
    password:                   # Replace with your DB password
    driver-class-name: com.mysql.cj.jdbc.Driver # Replace with the driver class name for your database
  jpa:
    hibernate:
      ddl-auto: update   # Use 'create', 'create-drop', 'update', or 'validate' depending on your need
    show-sql: true       # Shows SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect